/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.Auto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for AutoApi
 */
@Ignore
public class AutoApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final AutoApi api = new AutoApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Add a new auto to the dealer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addAutoTest() throws Exception {
        Auto body = null;
    ResponseEntity<Void> response = api.addAuto(body , accept);

        // TODO: test validations
    }
    
    /**
     * Deletes a auto
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAutoTest() throws Exception {
        Long autoId = null;
        String apiKey = null;
    ResponseEntity<Void> response = api.deleteAuto(autoId, apiKey , accept);

        // TODO: test validations
    }
    
    /**
     * Find auto by ID
     *
     * Returns a single auto
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAutoByIdTest() throws Exception {
        Long autoId = null;
    ResponseEntity<Auto> response = api.getAutoById(autoId , accept);

        // TODO: test validations
    }
    
    /**
     * Update an existing auto
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAutoTest() throws Exception {
        Auto body = null;
    ResponseEntity<Void> response = api.updateAuto(body , accept);

        // TODO: test validations
    }
    
}
