/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for DealerApi
 */
@Ignore
public class DealerApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final DealerApi api = new DealerApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Returns all autos
     *
     * Returns a collection of autos
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAutosTest() throws Exception {
    ResponseEntity<Map<String, Integer>> response = api.getAutos(  accept);

        // TODO: test validations
    }
    
    /**
     * Returns all employees
     *
     * Returns a collection of employees
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEmployeesTest() throws Exception {
    ResponseEntity<Map<String, Integer>> response = api.getEmployees(  accept);

        // TODO: test validations
    }
    
}
