/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for EmployeeApi
 */
@Ignore
public class EmployeeApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final EmployeeApi api = new EmployeeApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Add a new employee to the dealer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addEmployeeTest() throws Exception {
        Employee body = null;
    ResponseEntity<Void> response = api.addEmployee(body , accept);

        // TODO: test validations
    }
    
    /**
     * Deletes a employee
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteEmployeeTest() throws Exception {
        Long employeeId = null;
        String apiKey = null;
    ResponseEntity<Void> response = api.deleteEmployee(employeeId, apiKey , accept);

        // TODO: test validations
    }
    
    /**
     * Find employee by ID
     *
     * Returns a single employee
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEmployeeByIdTest() throws Exception {
        Long employeeId = null;
    ResponseEntity<Employee> response = api.getEmployeeById(employeeId , accept);

        // TODO: test validations
    }
    
    /**
     * Update an existing auto
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateEmployeeTest() throws Exception {
        Employee body = null;
    ResponseEntity<Void> response = api.updateEmployee(body , accept);

        // TODO: test validations
    }
    
}
