/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.prokarma.pkmst.controller;

import com.prokarma.pkmst.model.Employee;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
/**
 * Provides the info about api methods
 * @author pkmst
 *
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaPKMSTServerCodegen", date = "2020-11-14T17:17:21.195Z")

@Api(value = "Employee", description = "the Employee API")
public interface EmployeeApi {

    @ApiOperation(value = "Add a new employee to the dealer", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "autodealer_auth", scopes = {
            @AuthorizationScope(scope = "read:employees", description = "read employee"),
            @AuthorizationScope(scope = "write:employees", description = "modify employee in your account")
            })
    }, tags={ "employee", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/employee",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addEmployee(@ApiParam(value = "Employee object that needs to be added to the autodealer" ,required=true )   @RequestBody Employee body, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Deletes a employee", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "autodealer_auth", scopes = {
            @AuthorizationScope(scope = "read:employees", description = "read employee"),
            @AuthorizationScope(scope = "write:employees", description = "modify employee in your account")
            })
    }, tags={ "employee", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Employee not found") })
    @RequestMapping(value = "/employee/{employeeId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteEmployee(@ApiParam(value = "Employee id to delete",required=true ) @PathVariable("employeeId") Long employeeId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Find employee by ID", notes = "Returns a single employee", response = Employee.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "employee", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Employee.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Employee not found") })
    @RequestMapping(value = "/employee/{employeeId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Employee> getEmployeeById(@ApiParam(value = "ID of employee to return",required=true ) @PathVariable("employeeId") Long employeeId, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;


    @ApiOperation(value = "Update an existing auto", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "autodealer_auth", scopes = {
            @AuthorizationScope(scope = "read:employees", description = "read employee"),
            @AuthorizationScope(scope = "write:employees", description = "modify employee in your account")
            })
    }, tags={ "employee", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Employee not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/employee",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateEmployee(@ApiParam(value = "Employee object that needs to be updated" ,required=true )   @RequestBody Employee body, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
