/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Auto;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * API tests for AutoApi
 */
public class AutoApiTest {

    private final AutoApi api = new AutoApi();
    private static final Auto SPECTRA = new Auto(1L, "kia", "spectra", 2007L);
    private static final Auto SPORTAGE = new Auto(2L, "kia", "sportage", 2006L);

    @Before
    public void beforeAll() throws ApiException {
        api.addAuto(SPECTRA);
    }
    
    /**
     * Deletes a auto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addThenDeleteAutoTest() throws ApiException {
        String apiKey = null;
        api.addAuto(SPORTAGE);
        Assert.assertEquals(SPORTAGE, api.getAutoById(SPORTAGE.getId()));
        api.deleteAuto(SPORTAGE.getId(), apiKey);
        Assert.assertNull(api.getAutoById(SPORTAGE.getId()));
    }
    
    /**
     * Find auto by ID
     *
     * Returns a single auto
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAutoByIdTest() throws ApiException {
        Auto response = api.getAutoById(SPECTRA.getId());
        Assert.assertEquals(SPECTRA, response);
    }
    
    /**
     * Update an existing auto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAutoTest() throws ApiException {
        Long newYear = 2008L;
        Auto newAuto = new Auto(1L, "kia", "spectra", newYear);
        api.updateAuto(newAuto);
        Assert.assertEquals(newAuto, api.getAutoById(newAuto.getId()));
    }
    
}
