/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DealerApi
 */
@Ignore
public class DealerApiTest {

    private final DealerApi api = new DealerApi();

    
    /**
     * Returns all autos
     *
     * Returns a collection of autos
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAutosTest() throws ApiException {
        Map<String, Integer> response = api.getAutos();

        // TODO: test validations
    }
    
    /**
     * Returns all employees
     *
     * Returns a collection of employees
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmployeesTest() throws ApiException {
        Map<String, Integer> response = api.getEmployees();

        // TODO: test validations
    }
    
}
