/*
 * Autodealer
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeeApi
 */
@Ignore
public class EmployeeApiTest {

    private final EmployeeApi api = new EmployeeApi();

    
    /**
     * Add a new employee to the dealer
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addEmployeeTest() throws ApiException {
        Employee body = null;
        api.addEmployee(body);

        // TODO: test validations
    }
    
    /**
     * Deletes a employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEmployeeTest() throws ApiException {
        Long employeeId = null;
        String apiKey = null;
        api.deleteEmployee(employeeId, apiKey);

        // TODO: test validations
    }
    
    /**
     * Find employee by ID
     *
     * Returns a single employee
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmployeeByIdTest() throws ApiException {
        Long employeeId = null;
        Employee response = api.getEmployeeById(employeeId);

        // TODO: test validations
    }
    
    /**
     * Update an existing auto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateEmployeeTest() throws ApiException {
        Employee body = null;
        api.updateEmployee(body);

        // TODO: test validations
    }
    
}
